/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_io_compress_dsrc_Hello */

#ifndef _Included_org_apache_hadoop_io_compress_dsrc_Hello
#define _Included_org_apache_hadoop_io_compress_dsrc_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_io_compress_dsrc_Hello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_compress_dsrc_Hello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
